--- Day 3: Gear Ratios ---\
You and the Elf eventually reach a gondola lift station; he says the gondola lift will take you up to the water source, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

In [168]:
input = ['467..114..',
         '...*......',
         '..35..633.',
         '......#...',
         '617*......',
         '.....+.58.',
         '..592.....',
         '......755.',
         '...$.*....',
         '.664.598..']
print(input)

['467..114..', '...*......', '..35..633.', '......#...', '617*......', '.....+.58.', '..592.....', '......755.', '...$.*....', '.664.598..']


In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

In [172]:
import re

#directions represent the 8 directions to check for a symbol
directions:list[tuple[int,int]] = [
    (-1, -1), (-1, 0), (-1, 1), #top layer
    (0, -1),           (0, 1), #middle layer
    (1, -1),  (1, 0),  (1, 1) #bottom layer
]

def is_valid_symbol(char: str) -> bool:
    return not (char == '.' or char.isdigit())

def is_next_to_symbol(j: int, k: int) -> bool:
    found = False
    for dx, dy in directions:
        neighbor_j = min(max(0, j + dx), len(input) - 1)
        neighbor_k = min(max(0, k + dy), len(input[0]) - 1)
        if is_valid_symbol(input[neighbor_j][neighbor_k]):
            return True
    return found

In [173]:
def part1(input: list[str]) -> int:
    """_summary_

    Args:
        input (list[str]): _description_

    Returns:
        int: _description_
    """
    sum = 0
    num = ''
    symbol = False
    for j, row in enumerate(input):
        for k, char in enumerate(row):
            if char.isdigit():
                if symbol is False and is_next_to_symbol(j, k):
                    symbol = True
                num += char
            else:
                sum += int(num) if symbol and num else 0
                symbol = False
                num = ''
    return sum


print("Result expected: 4361\nGot:", part1(input))


Result expected: 4361
Got: 537732


--- Part Two ---\
The engineer finds the missing part and installs it in the engine! As the engine springs to life, you jump in the closest gondola, finally ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still wrong? Fortunately, the gondola has a phone labeled "help", so you pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out the window. There stands the engineer, holding a phone in one hand and waving with the other. You're going so slowly that you haven't even left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the engine is wrong. A gear is any * symbol that is adjacent to exactly two part numbers. Its gear ratio is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:

In [329]:
input = ["467..114..",
         "...*......",
         "..35..633.",
         "......#...",
         "617*......",
         ".....+.58.",
         "..592.....",
         "......755.",
         "...$.*....",
         ".664.598.."]
print(input)

['467..114..', '...*......', '..35..633.', '......#...', '617*......', '.....+.58.', '..592.....', '......755.', '...$.*....', '.664.598..']


In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835.

In [330]:
def is_gear(char: str) -> bool:
    return char == '*'

def is_next_to_symbol(j: int, k: int) -> bool:
    found = []
    for dx, dy in directions:
        neighbor_j = min(max(0, j + dx), len(input) - 1)
        neighbor_k = min(max(0, k + dy), len(input[0]) - 1)
        if is_gear(input[neighbor_j][neighbor_k]):
            found.append((neighbor_j, neighbor_k))
    return found

def multiply_list(input: list[int]) -> int:
    """
    Multiply all the elements in a list

    Args:
        input (list[int]): List of integers to multiply

    Returns:
        int: Result of the multiplication
        
    Example: multiply_list([1,2,3,4]) -> 24
        
    Author: @jotanmiguel
    """
    result = 1
    for i in input:
        result *= i
    return result


In [333]:
def part2(input: list[str]) -> int:
    num:str = ''
    gears:list = []
    numbers:dict = {}
    for j, row in enumerate(input):
        for k, char in enumerate(row):
            if char.isdigit():
                num += char
                gears = is_next_to_symbol(j, k) if len(is_next_to_symbol(j, k)) > 0 else gears
            else:
                if num:
                    for gear in gears:
                        if gear not in numbers.keys():
                            numbers[gear] = [int(num)]
                        else:
                            numbers[gear].append(int(num))
                num = ''
                gears = []
    return sum([multiply_list(numbers[key]) for key in numbers.keys() if len(numbers[key]) > 1])

print("Result expected: 467835\nGot:", part2(input))

Result expected: 467835
Got: 467835


So let's see if we can help the engineer by finding the sum of all part numbers and the sum of all gear ratios.

In [336]:
import aoc_utils as utils

input = utils.readInputFile("input.txt")
print("Solving part 1")
print("Result: " + str(part1(input)))
print("Solving part 2")
print("Result: " + str(part2(input)))

Solving part 1
Result: 353155
Solving part 2
Result: 84883664
